### ISSUE TITLE
Include out-of-bounds elements in mismatch calculation

### ISSUE THREAD

**Issue by Cody-G** [HolyLab/RegisterMismatch.jl#7]
On closer look it seems that #6  has taken away a nice feature, the ability to include in the `mismatch` calculation array elements that are out-of-bounds when a SubArray is passed.  (By intelligently using elements of the parent array).  Was this intentional?  I think it was a valuable feature, though perhaps our implementation was a bit dangerous and could be improved with modern Julia indexing flexibility.  The script below demonstrates the issue.  The tests fail now, but they pass if I checkout older versions of RegisterMismatch and RegisterMismatchCommon:

```julia
using RegisterMismatch, OffsetArrays
using Test

#Test whether mismatch uses array elements from the parent array that are out-of-bounds in the view

fixed = OffsetArray(rand(10,10), (-1:8, -1:8))
moving = OffsetArray(rand(10,10), (-2:7, -2:7))
m_view = view(moving, -1:7, -1:7)
m_noview = moving[-1:7,-1:7]
f_view = view(fixed, -1:7, -1:7)
f_noview = fixed[-1:7, -1:7]

#..test for OffsetArrays
mm_v = mismatch(f_view,m_view,(2,2))
mm_nv = mismatch(f_noview,m_noview,(2,2))
@test !all(mm_v.==mm_nv)


#..test for plain arrays
m_view = view(parent(moving), 2:10, 2:10)
m_noview = parent(moving)[2:10,2:10]
f_view = view(parent(fixed), 1:9, 1:9)
f_noview = parent(fixed)[1:9, 1:9]

mm_v = mismatch(f_view,m_view,(2,2))
mm_nv = mismatch(f_noview,m_noview,(2,2))
@test !all(mm_v.==mm_nv)
```

**Comment by timholy** [comment]
Actually, #6 put us on better footing here. The only code changes required are to delete a bunch of `assertsamesize` statements. Going forward, you should let `fixed` be the region you want to match; it's OK if `moving` contains extra stuff.

**Comment by Cody-G** [comment]
Ah great, I was hoping we could get rid of those assertions!
